---
apiVersion: v1
kind: Service
metadata:
  name: microstore-api-gateway
  labels:
    app.kubernetes.io/instance: microstore
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/name: microstore-api-gateway
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: microstore
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app.kubernetes.io/name: microstore-api-gateway
